### ISSUE TITLE
Support for Erlang/OTP 20

### ISSUE THREAD

**Issue by ifoo** [nerves-project/nerves_system_qemu_arm#11]
When building with erlang/OTP version 20 I get the following error:

```
>  export MIX_TARGET=qemu_arm
> mix deps.get
....
> mix firmware
...
==> hello_nerves
** (Mix) Major version mismatch between host and target Erlang/OTP versions
  Host version: 20
  Target version: 19
This will likely cause Erlang code compiled for the target to fail in
unexpected ways. Install an Erlang OTP release that matches the target
version before continuing.
```

**Comment by GregMefford** [comment]
We require that your host OTP version (running on the machine that's building the firmware) match the version that will run on the target (embedded system). Since the currently-released versions of the supported Nerves Systems are using OTP 19, you need to use OTP 19 to build your firmware.

To make this process easier to manage and avoid having to uninstall/reinstall Erlang system-wide, we recommend using a version-management tool like `asdf` to easily switch between versions of your build tools, as described here: http://embedded-elixir.com/post/2017-05-23-using-asdf-vm/

**Comment by GregMefford** [comment]
I should have also mentioned that we will support OTP 20 in the future as a part of a future System release, but the constraint of matching your host OTP version will likely continue to exist then. So at that point, OTP 19 will no longer be supported on the host for that System version.

**Comment by GregMefford** [comment]
I've opened a matching issue here for better visibility across the Nerves ecosystem: https://github.com/nerves-project/nerves/issues/139.

Thanks for taking the time to document this issue! 🎈
